CREATE TABLE patents(id SERIAL PRIMARY KEY, patentNum INTEGER, filingDate DATE)
CREATE TABLE cip(id SERIAL PRIMARY KEY, CIPNum INTEGER, CIPfilingDate DATE, patentNum INTEGER)
CREATE TABLE users(id SERIAL PRIMARY KEY, firstname VARCHAR, lastname VARCHAR, userID INTEGER)
CREATE TABLE documents(id SERIAL PRIMARY KEY, DocfilingDate INTEGER, document BINARY)